version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todo-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - app-tier
    depends_on:
      - psqldb

  psqldb:
    image: postgres:16
    ports:
      - "5432:5432"
    networks:
      - app-tier
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASS
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
